language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing"

# Scripts à exécuter en guise de tests
before_script:
  - echo "none"

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed oury011/udagram-api-feed:latest
  - docker tag udagram-api-user oury011/udagram-api-user:latest
  - docker tag udagram-reverseproxy oury011/udagram-reverseproxy:latest
  - docker tag udagram-frontend:local oury011/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tressisson/udagram-api-feed:latest
  - docker push tressisson/udagram-api-user:latest
  - docker push tressisson/udagram-reverseproxy:latest
  - docker push tressisson/udagram-frontend:latest