language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing"

# Scripts à exécuter en guise de tests
before_script:
  - echo "none"

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed tressisson/udagram-api-feed:v1
  - docker tag udagram-api-user tressisson/udagram-api-user:v1
  - docker tag udagram-reverseproxy tressisson/reverseproxy:v1
  - docker tag udagram-frontend:local tressisson/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tressisson/udagram-api-feed:v1
  - docker push tressisson/udagram-api-user:v1
  - docker push tressisson/reverseproxy:v1
  - docker push tressisson/udagram-frontend:v1